---
name: Deploy Logic App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      
      - name: .NET Restore
        run: dotnet restore $GITHUB_WORKSPACE/src/src.csproj
      
      - name: .NET Build
        run: dotnet build $GITHUB_WORKSPACE/src/src.csproj --configuration Release
      
      - name: .NET Publish
        run: dotnet publish $GITHUB_WORKSPACE/src/src.csproj --configuration Release --output $GITHUB_WORKSPACE/output
      
      - uses: actions/upload-artifact@v2
        with:
          name: logic-app-package
          path: output
  deploy:
    runs-on: ubuntu-latest

    needs: build

    env:
      LOGIC_APP_NAME: 'logic-app-preview-la'
      STORAGE_ACCOUNT_NAME: 'logicapppreviewsto'
      ASP_NAME: 'logic-app-preview-asp'
      INSIGHTS_NAME: 'logic-app-preview-ins'
      LOCATION: 'northeurope'
      RESOURCE_GROUP: 'logic-apps-preview'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v4.1.7
        with:
          name: logic-app-package
          path: logic-app-package

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: Azure/arm-deploy@v1

        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: infrastructure/arm-template.json
          deploymentMode: Incremental
          parameters: logicAppName=${{ env.LOGIC_APP_NAME }} storageAccountName=${{ env.STORAGE_ACCOUNT_NAME }} appServicePlanName=${{ env.ASP_NAME }} insightsName=${{ env.INSIGHTS_NAME }} location=${{ env.LOCATION }}

      - name: Deploy Logic App
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ env.LOGIC_APP_NAME }}
          package: logic-app-package